### ISSUE TITLE
支持 👍 7 次或以上 HP +7

### ISSUE THREAD

**Issue by sorrycc** [earlyBirdCamp/earlyBirdCamp#3]
* [ ] 添加额外 CI 统计文章的 reaction 信息
* [ ] 根据文章 reaction 数据进行计算

**Comment by CJY0208** [comment]
好奇，目前还没有条件实施

查了文档，可能的动作如下
1. 定位到 [/scripts/actions.ts](https://github.com/earlyBirdCamp/earlyBirdCamp/blob/master/scripts/action.ts#L54-L88) 文件的 `getData` 函数中进行改动

2. 使用 [issues-list-comments](https://octokit.github.io/rest.js/v17#issues-list-comments) api 拉取指定 issue 的 comments 列表

3. 使用 [reactions-list-for-issue-comment](https://octokit.github.io/rest.js/v17#reactions-list-for-issue-comment) api 拉取第一条 comment 的 👍 数量

   `content` 参数：`+1`，参考 [reaction-types](https://developer.github.com/v3/reactions/#reaction-types) 继续配置

4.  `member.hp += Math.floor({👍 数量} / 7)`

**Comment by sorrycc** [comment]
已实现。
